name: tuxshare
description: TuxShare is an open-source, cross-platform file sharing app that lets you securely and effortlessly transfer files between devices on the same network—no internet required.
version: 0.1.2
repository: https://github.com/TechTowers/tuxshare

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  ansix: ^0.3.4
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
